# https://github.com/julia-actions/julia-buildpkg
name: Run tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@v1
        with:
          version: stable
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1